#!/bin/bash

topdir=$(pwd)

podman_pass=false
buildah_pass=false

printf "Attempting to build using podman\n"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -

podman system migrate
podman image rm podman-test-hello --force > /dev/null 2>&1
if podman --storage-opt overlay.ignore_chown_errors=true build $topdir -t podman-test-hello --quiet ; then
	printf "Podman build succeeded\n"
	podman_pass=true
	printf "Deleting image... "
	podman image rm podman-test-hello --force > /dev/null 2>&1
	printf "done.\n"
else
	printf "Podman build failed\n"
fi

printf '%*s\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -

printf "Attempting to build using buildah\n"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -

buildah rmi buildah-test-hello > /dev/null 2>&1
if buildah bud --quiet -t buildah-test-hello $topdir/Dockerfile ; then
	printf "Buildah bud succeeded\n"
	buildah_pass=true
	printf "Deleting image... "
	buildah rmi buildah-test-hello > /dev/null 2>&1
	printf "done.\n"
else
	printf "Buildah bud failed\n\n"
fi

printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
if [ "$podman_pass" = true ] && [ "$buildah_pass" = true ] ; then
	printf "TEST PASSED\n"
else
	printf "TEST FAILED\n"
fi
