#!/bin/bash
printf "Save/load test\n"
printf '%*s\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =

printf "Building image.. "
if podman build --root=/tmp/podman_tmp --runroot=/tmp/podman_tmp ./base_dockerfile -t "load_test" ; then
        printf "done\n"
else
        printf "failed\n"
        echo "TEST FAILED"
        exit 1
fi
printf "Saving to testing.rar.. "
if podman save load_test  --root=/tmp/podman_tmp -o testing.tar ; then
        printf "done\n"
else
        printf "failed\n"
        echo "TEST FAILED"
        exit 1
fi

podman image rm load_test  --root=/tmp/podman_tmp --force >/dev/null 2>&1

podman load --root=/tmp/podman_tmp -i testing.tar --quiet

uid_pass=
write_pass=

printf "Create a file from within the container... "
if podman run  --root=/tmp/podman_tmp  -v /scratch/ismailiy/test-podman:/tests load_test bash -c "touch /tests/my_uid" ; then
        printf "done\n"
else
        printf "failed\n"
        echo "TEST FAILED"
        exit 1
fi

my_id=$(id -u $USER)
file_owner=$(stat -c '%u' /scratch/ismailiy/test-podman/my_uid)
printf "Check if file owner uid is the same as current uid... "
if [ "$my_id" -eq "$file_owner" ] ; then
        uid_pass=true
        printf "done\n"
else
        printf "failed\n"
fi

printf "Check if file is writable from outside of the container... "
if touch /scratch/ismailiy/test-podman/my_uid ; then
        write_pass=true
        printf "done\n"
else
        printf "failed\n"
fi

if [ $uid_pass -a $write_pass ] ; then
        echo TEST PASSED
else
        echo TEST FAILED
fi

rm /scratch/ismailiy/test-podman/my_uid
rm "testing.tar"
