#!/bin/bash
printf "Setting up uid and gid ranges for $SUDO_USER in /etc/subuid and /etc/subgid/... "

usermod --add-subuids 100000-165535 $SUDO_USER
usermod --add-subgids 100000-165535 $SUDO_USER

podman system migrate

printf "done.\n\n"


